version: '3'
services:
  customer:
    build: ./services/customer-service
    image: loopback-example-facade/customer-service
    ports:
      - "3001:80"
    networks:
      app-net:
        aliases:
          - customer
  account:
    build: ./services/account-service
    image: loopback-example-facade/account-service
    ports:
      - "3002:80"
    networks:
      app-net:
        aliases:
          - account-service
  transaction:
    build: ./services/transaction-service
    image: loopback-example-facade/transaction-service
    ports:
      - "3003:80"
    networks:
      app-net:
        aliases:
          - transaction-service
  facade:
    build: ./services/facade
    image: loopback-example-facade/facade
    ports:
      - "3000:80"
    links:
      - customer
      - account
      - transaction
    networks:
      app-net:
        aliases:
          - facade
          - account-facade
  vitals:
    build: ./services/health-check
    image: loopback-example-facade/health-check
    ports:
      - "3004:80"
    links:
      - customer
      - account
      - transaction
      - facade
    networks:
      app-net:
        aliases:
          - vitals
networks:
  app-net:
    driver: bridge